### PR TITLE
Migrate to Github Actions

### PR DESCRIPTION
**Pull request by crobibero**
Very hard to test without having the keys and whatnot, but here's a start :)

### CODE REVIEW

**Comment by anthonylavado** [comment]
Ah, my fork has this part that actually builds the Swift menu bar app itself:
https://github.com/anthonylavado/jellyfin-server-macos/blob/master/.github/workflows/xcodebuild.yml

I would probably use the same variables.

So overall it's these steps:

- [x] build/download server & web
- [x] download correct FFmpeg/FFprobe
- [x] build menu bar app
- [x] Place server, web, FFmpeg, FFprobe in the correct directories
- [ ] Sign everything
- [ ] Package as DMG
- [ ] Upload to Apple for notarization
- [ ] Staple notarization ticket to DMG (optional)
- [ ] Upload artifacts

I'll have a proper look at this later to see where we need to fit things in :-)

**Comment by crobibero** [comment]
I think I got the first 4 steps done and stopped when I got to signing since I don't have the certs :)

**Comment by anthonylavado** [comment]
@crobibero Can you enable pushes? I have changes to make :-)

**Comment by crobibero** [comment]
Edits by maintainers is already enabled..

If you're working on it tonight feel free to create a new PR. If not I can recreate the PR tomorrow to see if that helps

**Comment by crobibero** [comment]
Closing in favor of #52

**Pull request closed without merging**
